# Generated by Django 5.2 on 2025-09-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zamestnanec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria', models.CharField(choices=[('IN', 'Interní'), ('EX', 'Externí'), ('BR', 'Brigádnici')], max_length=2)),
                ('meno', models.CharField(max_length=100)),
                ('priezvisko', models.CharField(max_length=100)),
                ('datum_narodenia', models.DateField()),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('zmluva', models.TextField()),
                ('zavazky', models.TextField()),
            ],
        ),
    ]
