# Generated by Django 5.2 on 2025-09-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evidencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dodavatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontaktna_osoba', models.CharField(max_length=100, verbose_name='Kontaktná osoba')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefón')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('ostatne', models.TextField(blank=True, verbose_name='Ostatné')),
            ],
            options={
                'verbose_name': 'Dodávatel',
                'verbose_name_plural': 'Dodávatelia',
            },
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='datum_narodenia',
            field=models.DateField(verbose_name='Dátum narodenia'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='kategoria',
            field=models.CharField(choices=[('IN', 'Interní'), ('EX', 'Externí'), ('BR', 'Brigádnici')], max_length=2, verbose_name='Kategória'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='meno',
            field=models.CharField(max_length=100, verbose_name='Meno'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='priezvisko',
            field=models.CharField(max_length=100, verbose_name='Priezvisko'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='telefon',
            field=models.CharField(max_length=20, verbose_name='Telefón'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='zavazky',
            field=models.TextField(verbose_name='Záväzky voči firme'),
        ),
        migrations.AlterField(
            model_name='zamestnanec',
            name='zmluva',
            field=models.TextField(verbose_name='Zmluva'),
        ),
    ]
