# Generated by Django 5.2 on 2025-09-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evidencia', '0002_dodavatel_alter_zamestnanec_datum_narodenia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kontaktna_osoba', models.CharField(max_length=100, verbose_name='Kontaktná osoba')),
                ('Telefon', models.CharField(max_length=20, verbose_name='Telefón')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Ostatne', models.TextField(blank=True, verbose_name='Ostatné')),
            ],
            options={
                'verbose_name': 'Zákazník',
                'verbose_name_plural': 'Zákazníci',
            },
        ),
    ]
