# Generated by Django 5.2.6 on 2025-09-23 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evidencia', '0003_zakaznik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Sklad',
                'verbose_name_plural': 'Sklady',
            },
        ),
        migrations.AlterModelOptions(
            name='dodavatel',
            options={'verbose_name': 'Dodávateľ', 'verbose_name_plural': 'Dodávatelia'},
        ),
        migrations.CreateModel(
            name='SpotrebnyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('mnozstvo', models.PositiveIntegerField(default=0)),
                ('sklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='Evidencia.sklad')),
            ],
            options={
                'verbose_name': 'Spotrebný materiál',
                'verbose_name_plural': 'Spotrebný materiál',
            },
        ),
        migrations.CreateModel(
            name='Stroje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('vyrobne_cislo', models.CharField(blank=True, max_length=100, null=True)),
                ('sklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stroje', to='Evidencia.sklad')),
            ],
            options={
                'verbose_name': 'Stroj',
                'verbose_name_plural': 'Stroje',
            },
        ),
    ]
