# Generated by Django 5.2.6 on 2025-09-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evidencia', '0004_sklad_alter_dodavatel_options_spotrebnymaterial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotrebnymaterial',
            name='sklad',
        ),
        migrations.DeleteModel(
            name='Stroje',
        ),
        migrations.DeleteModel(
            name='Sklad',
        ),
        migrations.DeleteModel(
            name='SpotrebnyMaterial',
        ),
    ]
