# Generated by Django 5.2.6 on 2025-09-23 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evidencia', '0005_remove_spotrebnymaterial_sklad_delete_stroje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpotrebnyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('sklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialy', to='Evidencia.sklad')),
            ],
        ),
        migrations.CreateModel(
            name='Stroj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('sklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stroje', to='Evidencia.sklad')),
            ],
        ),
    ]
