# Generated by Django 5.2.6 on 2025-09-23 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evidencia', '0006_sklad_spotrebnymaterial_stroj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sklad',
            options={'verbose_name': 'Sklad', 'verbose_name_plural': 'Sklady'},
        ),
        migrations.AlterModelOptions(
            name='spotrebnymaterial',
            options={'verbose_name': 'Spotrebný materiál', 'verbose_name_plural': 'Spotrebné materiály'},
        ),
        migrations.AlterModelOptions(
            name='stroj',
            options={'verbose_name': 'Stroj', 'verbose_name_plural': 'Stroje'},
        ),
        migrations.CreateModel(
            name='Poruchovydiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('sklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diely', to='Evidencia.sklad')),
            ],
            options={
                'verbose_name': 'Poruchový diel',
                'verbose_name_plural': 'Poruchové diely',
            },
        ),
    ]
