# Generated by Django 5.2.6 on 2025-09-23 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evidencia', '0007_alter_sklad_options_alter_spotrebnymaterial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoruchovaElektrovyzbroj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriove_cislo', models.CharField(max_length=100, verbose_name='Sériové číslo')),
                ('pocet_na_sklade', models.PositiveIntegerField(default=0, verbose_name='Počet na sklade')),
                ('diel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elektrovyzbroje', to='Evidencia.poruchovydiel')),
            ],
            options={
                'verbose_name': 'Elektrovýzbroj',
                'verbose_name_plural': 'Elektrovýzbroje',
            },
        ),
        migrations.CreateModel(
            name='PoruchovaSaciaKlapka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriove_cislo', models.CharField(max_length=100, verbose_name='Sériové číslo')),
                ('pocet_na_sklade', models.PositiveIntegerField(default=0, verbose_name='Počet na sklade')),
                ('diel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacie_klapky', to='Evidencia.poruchovydiel')),
            ],
            options={
                'verbose_name': 'Sacia klapka',
                'verbose_name_plural': 'Sacie klapky',
            },
        ),
        migrations.CreateModel(
            name='PoruchoveOstatne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriove_cislo', models.CharField(max_length=100, verbose_name='Sériové číslo')),
                ('pocet_na_sklade', models.PositiveIntegerField(default=0, verbose_name='Počet na sklade')),
                ('diel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ostatne_diely', to='Evidencia.poruchovydiel')),
            ],
            options={
                'verbose_name': 'Ostatný diel',
                'verbose_name_plural': 'Ostatné diely',
            },
        ),
        migrations.CreateModel(
            name='PoruchovyRiadiaciModul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriove_cislo', models.CharField(max_length=100, verbose_name='Sériové číslo')),
                ('pocet_na_sklade', models.PositiveIntegerField(default=0, verbose_name='Počet na sklade')),
                ('diel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riadiace_moduly', to='Evidencia.poruchovydiel')),
            ],
            options={
                'verbose_name': 'Riadiaci modul',
                'verbose_name_plural': 'Riadiace moduly',
            },
        ),
        migrations.CreateModel(
            name='PoruchovySnimacKabelaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriove_cislo', models.CharField(max_length=100, verbose_name='Sériové číslo')),
                ('pocet_na_sklade', models.PositiveIntegerField(default=0, verbose_name='Počet na sklade')),
                ('diel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snimace_kabelaze', to='Evidencia.poruchovydiel')),
            ],
            options={
                'verbose_name': 'Snímač + kábel',
                'verbose_name_plural': 'Snímače + kabeláž',
            },
        ),
        migrations.CreateModel(
            name='PoruchovyVentilatorMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriove_cislo', models.CharField(max_length=100, verbose_name='Sériové číslo')),
                ('pocet_na_sklade', models.PositiveIntegerField(default=0, verbose_name='Počet na sklade')),
                ('diel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventilatory_motory', to='Evidencia.poruchovydiel')),
            ],
            options={
                'verbose_name': 'Ventilátor a elektromotor',
                'verbose_name_plural': 'Ventilátory a elektromotory',
            },
        ),
    ]
