# Generated by Django 5.2.6 on 2025-09-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evidencia', '0008_poruchovaelektrovyzbroj_poruchovasaciaklapka_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poruchovydiel',
            options={'verbose_name': 'V skratke o mne, Šuflíku poruchových dielov', 'verbose_name_plural': 'Poruchové diely'},
        ),
        migrations.RemoveField(
            model_name='poruchovydiel',
            name='nazov',
        ),
        migrations.AddField(
            model_name='poruchovaelektrovyzbroj',
            name='kto_som',
            field=models.TextField(blank=True, verbose_name='V skratke o mne'),
        ),
        migrations.AddField(
            model_name='poruchovasaciaklapka',
            name='kto_som',
            field=models.TextField(blank=True, verbose_name='V skratke o mne'),
        ),
        migrations.AddField(
            model_name='poruchoveostatne',
            name='kto_som',
            field=models.TextField(blank=True, verbose_name='V skratke o mne'),
        ),
        migrations.AddField(
            model_name='poruchovyriadiacimodul',
            name='kto_som',
            field=models.TextField(blank=True, verbose_name='V skratke o mne'),
        ),
        migrations.AddField(
            model_name='poruchovysnimackabelaz',
            name='kto_som',
            field=models.TextField(blank=True, verbose_name='V skratke o mne'),
        ),
        migrations.AddField(
            model_name='poruchovyventilatormotor',
            name='kto_som',
            field=models.TextField(blank=True, verbose_name='V skratke o mne'),
        ),
    ]
