# Generated by Django 5.2.6 on 2025-09-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evidencia', '0009_alter_poruchovydiel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poruchovydiel',
            options={'verbose_name': 'V skratke o mne', 'verbose_name_plural': 'Poruchové diely'},
        ),
    ]
