# Generated by Django 5.2.6 on 2025-09-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evidencia', '0010_alter_poruchovydiel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='poruchovydiel',
            name='nazov',
            field=models.CharField(default='Ahoj. Som šuflík poruchových dielov :)', max_length=100),
        ),
    ]
