# Generated by Django 5.2.6 on 2025-09-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evidencia', '0011_poruchovydiel_nazov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poruchovydiel',
            name='nazov',
        ),
    ]
