# Generated by Django 5.2.6 on 2025-09-25 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evidencia', '0012_remove_poruchovydiel_nazov'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poruchovasaciaklapka',
            options={'verbose_name': 'Solenoid', 'verbose_name_plural': 'Solenoidy'},
        ),
        migrations.AlterModelOptions(
            name='spotrebnymaterial',
            options={'verbose_name': 'V skratke o mne', 'verbose_name_plural': 'Spotrebné náhradné diely'},
        ),
        migrations.RemoveField(
            model_name='spotrebnymaterial',
            name='nazov',
        ),
        migrations.CreateModel(
            name='SpotrebnaSaciaKlapka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriove_cislo', models.CharField(max_length=100, verbose_name='Sériové číslo')),
                ('pocet_na_sklade', models.PositiveIntegerField(default=0, verbose_name='Počet na sklade')),
                ('kto_som', models.TextField(blank=True, verbose_name='V skratke o mne')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacie_klapky', to='Evidencia.spotrebnymaterial')),
            ],
            options={
                'verbose_name': 'Sacia klapka',
                'verbose_name_plural': 'Sacie klapky',
            },
        ),
        migrations.CreateModel(
            name='SpotrebnaSadaVentilov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriove_cislo', models.CharField(max_length=100, verbose_name='Sériové číslo')),
                ('pocet_na_sklade', models.PositiveIntegerField(default=0, verbose_name='Počet na sklade')),
                ('kto_som', models.TextField(blank=True, verbose_name='V skratke o mne')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sady_ventilov', to='Evidencia.spotrebnymaterial')),
            ],
            options={
                'verbose_name': 'Sada spätných klapiek, oilstop ventilov a ventilov minimálnych tlakov',
                'verbose_name_plural': 'Sady spätných klapiek a ventilov',
            },
        ),
        migrations.CreateModel(
            name='SpotrebnaSpojka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriove_cislo', models.CharField(max_length=100, verbose_name='Sériové číslo')),
                ('pocet_na_sklade', models.PositiveIntegerField(default=0, verbose_name='Počet na sklade')),
                ('kto_som', models.TextField(blank=True, verbose_name='V skratke o mne')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spojky', to='Evidencia.spotrebnymaterial')),
            ],
            options={
                'verbose_name': 'Spojka',
                'verbose_name_plural': 'Spojky',
            },
        ),
        migrations.CreateModel(
            name='SpotrebneOstatne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriove_cislo', models.CharField(max_length=100, verbose_name='Sériové číslo')),
                ('pocet_na_sklade', models.PositiveIntegerField(default=0, verbose_name='Počet na sklade')),
                ('kto_som', models.TextField(blank=True, verbose_name='V skratke o mne')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ostatne_diely', to='Evidencia.spotrebnymaterial')),
            ],
            options={
                'verbose_name': 'Ostatný diel',
                'verbose_name_plural': 'Ostatné diely',
            },
        ),
        migrations.CreateModel(
            name='SpotrebnyKlinovyRemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriove_cislo', models.CharField(max_length=100, verbose_name='Sériové číslo')),
                ('pocet_na_sklade', models.PositiveIntegerField(default=0, verbose_name='Počet na sklade')),
                ('kto_som', models.TextField(blank=True, verbose_name='V skratke o mne')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klinove_remene', to='Evidencia.spotrebnymaterial')),
            ],
            options={
                'verbose_name': 'Klinový remeň',
                'verbose_name_plural': 'Klinové remene',
            },
        ),
        migrations.CreateModel(
            name='SpotrebnyOdkalovac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriove_cislo', models.CharField(max_length=100, verbose_name='Sériové číslo')),
                ('pocet_na_sklade', models.PositiveIntegerField(default=0, verbose_name='Počet na sklade')),
                ('kto_som', models.TextField(blank=True, verbose_name='V skratke o mne')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odkalovace', to='Evidencia.spotrebnymaterial')),
            ],
            options={
                'verbose_name': 'Odkalovač',
                'verbose_name_plural': 'Odkalovače',
            },
        ),
        migrations.CreateModel(
            name='SpotrebnyOlej',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriove_cislo', models.CharField(max_length=100, verbose_name='Sériové číslo')),
                ('pocet_na_sklade', models.PositiveIntegerField(default=0, verbose_name='Počet na sklade')),
                ('kto_som', models.TextField(blank=True, verbose_name='V skratke o mne')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oleje', to='Evidencia.spotrebnymaterial')),
            ],
            options={
                'verbose_name': 'Olej',
                'verbose_name_plural': 'Oleje',
            },
        ),
        migrations.CreateModel(
            name='SpotrebnyOlejovyFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriove_cislo', models.CharField(max_length=100, verbose_name='Sériové číslo')),
                ('pocet_na_sklade', models.PositiveIntegerField(default=0, verbose_name='Počet na sklade')),
                ('kto_som', models.TextField(blank=True, verbose_name='V skratke o mne')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olejove_filtre', to='Evidencia.spotrebnymaterial')),
            ],
            options={
                'verbose_name': 'Olejový filter',
                'verbose_name_plural': 'Olejové filtre',
            },
        ),
        migrations.CreateModel(
            name='SpotrebnyOlejovySeparator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriove_cislo', models.CharField(max_length=100, verbose_name='Sériové číslo')),
                ('pocet_na_sklade', models.PositiveIntegerField(default=0, verbose_name='Počet na sklade')),
                ('kto_som', models.TextField(blank=True, verbose_name='V skratke o mne')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olejove_separatory', to='Evidencia.spotrebnymaterial')),
            ],
            options={
                'verbose_name': 'Olejový separátor',
                'verbose_name_plural': 'Olejové separátory',
            },
        ),
        migrations.CreateModel(
            name='SpotrebnyVzduchovyFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriove_cislo', models.CharField(max_length=100, verbose_name='Sériové číslo')),
                ('pocet_na_sklade', models.PositiveIntegerField(default=0, verbose_name='Počet na sklade')),
                ('kto_som', models.TextField(blank=True, verbose_name='V skratke o mne')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vzduchove_filtre', to='Evidencia.spotrebnymaterial')),
            ],
            options={
                'verbose_name': 'Vzduchový filter',
                'verbose_name_plural': 'Vzduchové filtre',
            },
        ),
    ]
